[build-system]
requires = [
    "setuptools >= 57.0.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "nost_tools"
description = "Tools for New Observing Strategies Testbed (NOS-T) Applications"
authors = [
    {"name" = "Paul T. Grogan", "email" = "pgrogan@stevens.edu"}
]
readme = "README.md"
requires-python = ">=3.8"
license = {text = "BSD 3-Clause License"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
dependencies = [
    "numpy >= 1.24.1",
    "pandas >= 1.5.2",
    "python-dateutil >= 2.8.2",
    "ntplib >= 0.4.0",
    "paho-mqtt >= 1.6.1",
    "pydantic >= 1.10.4",
    "dash >= 2.6.1",
    "python-dotenv >= 0.21.0",
    "seaborn >= 0.12",
    "scipy >= 1.7.3",
    "skyfield >= 1.45"
]
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {attr = "nost_tools.__version__"}

[project.optional-dependencies]
docs = [
    "autodoc_pydantic >= 1.8.0",
    "sphinx >= 5.0.0, < 6.0.0",
    "sphinx_rtd_theme >= 1.1.0",
    "readthedocs-sphinx-search >= 0.1.0",
    "sphinx-copybutton >= 0.5.1",
    "docutils == 0.18.1",
    "dash >= 2.6.1",
    "python-dotenv >= 0.21.0",
    "seaborn >= 0.12",
    "scipy >= 1.7.3",
    "skyfield >= 1.45",
    "sphinx_design >= 0.4.1"
]
