[build-system]
requires = [
    "setuptools >= 57.0.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "nost_tools"
description = "Tools for Novel Observing Strategies Testbed (NOS-T) Applications"
authors = [
    {"name" = "Paul T. Grogan", "email" = "paul.grogan@asu.edu"},
    {"name" = "Emmanuel M. Gonzalez", "email" = "emmanuelgonzalez@asu.edu"}
]
readme = "README.md"
requires-python = ">=3.11"
license = {text = "BSD 3-Clause License"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta"
]
dependencies = [
    "ntplib",
    "numpy",
    "pandas",
    "pydantic >= 2, < 3",
    "python-dateutil",
    "pika", # >= 1.3.2",
    "python-dotenv", #>= 1.0.1",
    "pyyaml", #>= 6.0.2",
    "python-keycloak" #>= 4.2.1",
]
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {attr = "nost_tools.__version__"}

[project.optional-dependencies]
dev = [
    "black[jupyter] >= 24.2",
    "coverage",
    "pylint",
    "pylint-pydantic",
    "pytest"
]
examples = [
    "dash",
    "dash-daq",
    "flask",
    "python-dotenv",
    "scipy",
    "seaborn",
    "skyfield",
    "matplotlib >= 3.9.1",
    "xarray >= 2024.9.0",
    "rioxarray >= 0.17.0",
    "geopandas >= 1.0.1",
    "numpy >= 2.0.0",
    "netCDF4 >= 1.7", #1.7.1.post2",
    "aiobotocore >=2.5.4"
]
docs = [
    "autodoc_pydantic >= 2",
    "docutils",
    "readthedocs-sphinx-search",
    "sphinx >= 7",
    "sphinx_rtd_theme",
    "sphinx-copybutton",
    "sphinx_design",
]
